#include "keyboard_layout.h"
#include "ducky_script_keycodes.h"

static const char* layout_names[] = {
    [KeyboardLayoutUS] = "US",
    [KeyboardLayoutFR] = "FR",
    [KeyboardLayoutDE] = "DE",
    [KeyboardLayoutES] = "ES",
};

const char* keyboard_layout_get_name(KeyboardLayout layout) {
    if(layout >= KeyboardLayoutCount) return "??";
    return layout_names[layout];
}

// FR (AZERTY) ASCII to HID mapping.
// Uses SDK combined format: keycode | KEY_MOD_* flags.
static const uint16_t fr_asciimap[128] = {
    [' '] = HID_KEYBOARD_SPACEBAR,
    ['!'] = HID_KEYBOARD_SLASH,
    ['"'] = HID_KEYBOARD_3,
    ['#'] = HID_KEYBOARD_3 | KEY_MOD_RIGHT_ALT,
    ['$'] = HID_KEYBOARD_CLOSE_BRACKET,
    ['%'] = HID_KEYBOARD_APOSTROPHE | KEY_MOD_LEFT_SHIFT,
    ['&'] = HID_KEYBOARD_1,
    ['\''] = HID_KEYBOARD_4,
    ['('] = HID_KEYBOARD_5,
    [')'] = HID_KEYBOARD_MINUS,
    ['*'] = HID_KEYBOARD_BACKSLASH,
    ['+'] = HID_KEYBOARD_EQUAL_SIGN | KEY_MOD_LEFT_SHIFT,
    [','] = HID_KEYBOARD_M,
    ['-'] = HID_KEYBOARD_6,
    ['.'] = HID_KEYBOARD_COMMA | KEY_MOD_LEFT_SHIFT,
    ['/'] = HID_KEYBOARD_DOT | KEY_MOD_LEFT_SHIFT,
    ['0'] = HID_KEYBOARD_0 | KEY_MOD_LEFT_SHIFT,
    ['1'] = HID_KEYBOARD_1 | KEY_MOD_LEFT_SHIFT,
    ['2'] = HID_KEYBOARD_2 | KEY_MOD_LEFT_SHIFT,
    ['3'] = HID_KEYBOARD_3 | KEY_MOD_LEFT_SHIFT,
    ['4'] = HID_KEYBOARD_4 | KEY_MOD_LEFT_SHIFT,
    ['5'] = HID_KEYBOARD_5 | KEY_MOD_LEFT_SHIFT,
    ['6'] = HID_KEYBOARD_6 | KEY_MOD_LEFT_SHIFT,
    ['7'] = HID_KEYBOARD_7 | KEY_MOD_LEFT_SHIFT,
    ['8'] = HID_KEYBOARD_8 | KEY_MOD_LEFT_SHIFT,
    ['9'] = HID_KEYBOARD_9 | KEY_MOD_LEFT_SHIFT,
    [':'] = HID_KEYBOARD_DOT,
    [';'] = HID_KEYBOARD_COMMA,
    ['<'] = HID_KEYBOARD_NONUS_BACKSLASH,
    ['='] = HID_KEYBOARD_EQUAL_SIGN,
    ['>'] = HID_KEYBOARD_NONUS_BACKSLASH | KEY_MOD_LEFT_SHIFT,
    ['?'] = HID_KEYBOARD_M | KEY_MOD_LEFT_SHIFT,
    ['@'] = HID_KEYBOARD_0 | KEY_MOD_RIGHT_ALT,
    ['A'] = HID_KEYBOARD_Q | KEY_MOD_LEFT_SHIFT,
    ['B'] = HID_KEYBOARD_B | KEY_MOD_LEFT_SHIFT,
    ['C'] = HID_KEYBOARD_C | KEY_MOD_LEFT_SHIFT,
    ['D'] = HID_KEYBOARD_D | KEY_MOD_LEFT_SHIFT,
    ['E'] = HID_KEYBOARD_E | KEY_MOD_LEFT_SHIFT,
    ['F'] = HID_KEYBOARD_F | KEY_MOD_LEFT_SHIFT,
    ['G'] = HID_KEYBOARD_G | KEY_MOD_LEFT_SHIFT,
    ['H'] = HID_KEYBOARD_H | KEY_MOD_LEFT_SHIFT,
    ['I'] = HID_KEYBOARD_I | KEY_MOD_LEFT_SHIFT,
    ['J'] = HID_KEYBOARD_J | KEY_MOD_LEFT_SHIFT,
    ['K'] = HID_KEYBOARD_K | KEY_MOD_LEFT_SHIFT,
    ['L'] = HID_KEYBOARD_L | KEY_MOD_LEFT_SHIFT,
    ['M'] = HID_KEYBOARD_SEMICOLON | KEY_MOD_LEFT_SHIFT,
    ['N'] = HID_KEYBOARD_N | KEY_MOD_LEFT_SHIFT,
    ['O'] = HID_KEYBOARD_O | KEY_MOD_LEFT_SHIFT,
    ['P'] = HID_KEYBOARD_P | KEY_MOD_LEFT_SHIFT,
    ['Q'] = HID_KEYBOARD_A | KEY_MOD_LEFT_SHIFT,
    ['R'] = HID_KEYBOARD_R | KEY_MOD_LEFT_SHIFT,
    ['S'] = HID_KEYBOARD_S | KEY_MOD_LEFT_SHIFT,
    ['T'] = HID_KEYBOARD_T | KEY_MOD_LEFT_SHIFT,
    ['U'] = HID_KEYBOARD_U | KEY_MOD_LEFT_SHIFT,
    ['V'] = HID_KEYBOARD_V | KEY_MOD_LEFT_SHIFT,
    ['W'] = HID_KEYBOARD_Z | KEY_MOD_LEFT_SHIFT,
    ['X'] = HID_KEYBOARD_X | KEY_MOD_LEFT_SHIFT,
    ['Y'] = HID_KEYBOARD_Y | KEY_MOD_LEFT_SHIFT,
    ['Z'] = HID_KEYBOARD_W | KEY_MOD_LEFT_SHIFT,
    ['['] = HID_KEYBOARD_5 | KEY_MOD_RIGHT_ALT,
    ['\\'] = HID_KEYBOARD_8 | KEY_MOD_RIGHT_ALT,
    [']'] = HID_KEYBOARD_MINUS | KEY_MOD_RIGHT_ALT,
    ['^'] = HID_KEYBOARD_9 | KEY_MOD_RIGHT_ALT,
    ['_'] = HID_KEYBOARD_8,
    ['`'] = HID_KEYBOARD_7 | KEY_MOD_RIGHT_ALT,
    ['a'] = HID_KEYBOARD_Q,
    ['b'] = HID_KEYBOARD_B,
    ['c'] = HID_KEYBOARD_C,
    ['d'] = HID_KEYBOARD_D,
    ['e'] = HID_KEYBOARD_E,
    ['f'] = HID_KEYBOARD_F,
    ['g'] = HID_KEYBOARD_G,
    ['h'] = HID_KEYBOARD_H,
    ['i'] = HID_KEYBOARD_I,
    ['j'] = HID_KEYBOARD_J,
    ['k'] = HID_KEYBOARD_K,
    ['l'] = HID_KEYBOARD_L,
    ['m'] = HID_KEYBOARD_SEMICOLON,
    ['n'] = HID_KEYBOARD_N,
    ['o'] = HID_KEYBOARD_O,
    ['p'] = HID_KEYBOARD_P,
    ['q'] = HID_KEYBOARD_A,
    ['r'] = HID_KEYBOARD_R,
    ['s'] = HID_KEYBOARD_S,
    ['t'] = HID_KEYBOARD_T,
    ['u'] = HID_KEYBOARD_U,
    ['v'] = HID_KEYBOARD_V,
    ['w'] = HID_KEYBOARD_Z,
    ['x'] = HID_KEYBOARD_X,
    ['y'] = HID_KEYBOARD_Y,
    ['z'] = HID_KEYBOARD_W,
    ['{'] = HID_KEYBOARD_4 | KEY_MOD_RIGHT_ALT,
    ['|'] = HID_KEYBOARD_6 | KEY_MOD_RIGHT_ALT,
    ['}'] = HID_KEYBOARD_EQUAL_SIGN | KEY_MOD_RIGHT_ALT,
    ['~'] = HID_KEYBOARD_2 | KEY_MOD_RIGHT_ALT,
    ['\t'] = HID_KEYBOARD_TAB,
    ['\n'] = HID_KEYBOARD_RETURN,
};

// DE (QWERTZ) ASCII to HID mapping
static const uint16_t de_asciimap[128] = {
    [' '] = HID_KEYBOARD_SPACEBAR,
    ['!'] = HID_KEYBOARD_1 | KEY_MOD_LEFT_SHIFT,
    ['"'] = HID_KEYBOARD_2 | KEY_MOD_LEFT_SHIFT,
    ['#'] = HID_KEYBOARD_BACKSLASH,
    ['$'] = HID_KEYBOARD_4 | KEY_MOD_LEFT_SHIFT,
    ['%'] = HID_KEYBOARD_5 | KEY_MOD_LEFT_SHIFT,
    ['&'] = HID_KEYBOARD_6 | KEY_MOD_LEFT_SHIFT,
    ['\''] = HID_KEYBOARD_BACKSLASH | KEY_MOD_LEFT_SHIFT,
    ['('] = HID_KEYBOARD_8 | KEY_MOD_LEFT_SHIFT,
    [')'] = HID_KEYBOARD_9 | KEY_MOD_LEFT_SHIFT,
    ['*'] = HID_KEYBOARD_CLOSE_BRACKET | KEY_MOD_LEFT_SHIFT,
    ['+'] = HID_KEYBOARD_CLOSE_BRACKET,
    [','] = HID_KEYBOARD_COMMA,
    ['-'] = HID_KEYBOARD_SLASH,
    ['.'] = HID_KEYBOARD_DOT,
    ['/'] = HID_KEYBOARD_7 | KEY_MOD_LEFT_SHIFT,
    ['0'] = HID_KEYBOARD_0,
    ['1'] = HID_KEYBOARD_1,
    ['2'] = HID_KEYBOARD_2,
    ['3'] = HID_KEYBOARD_3,
    ['4'] = HID_KEYBOARD_4,
    ['5'] = HID_KEYBOARD_5,
    ['6'] = HID_KEYBOARD_6,
    ['7'] = HID_KEYBOARD_7,
    ['8'] = HID_KEYBOARD_8,
    ['9'] = HID_KEYBOARD_9,
    [':'] = HID_KEYBOARD_DOT | KEY_MOD_LEFT_SHIFT,
    [';'] = HID_KEYBOARD_COMMA | KEY_MOD_LEFT_SHIFT,
    ['<'] = HID_KEYBOARD_NONUS_BACKSLASH,
    ['='] = HID_KEYBOARD_0 | KEY_MOD_LEFT_SHIFT,
    ['>'] = HID_KEYBOARD_NONUS_BACKSLASH | KEY_MOD_LEFT_SHIFT,
    ['?'] = HID_KEYBOARD_MINUS | KEY_MOD_LEFT_SHIFT,
    ['@'] = HID_KEYBOARD_Q | KEY_MOD_RIGHT_ALT,
    ['A'] = HID_KEYBOARD_A | KEY_MOD_LEFT_SHIFT,
    ['B'] = HID_KEYBOARD_B | KEY_MOD_LEFT_SHIFT,
    ['C'] = HID_KEYBOARD_C | KEY_MOD_LEFT_SHIFT,
    ['D'] = HID_KEYBOARD_D | KEY_MOD_LEFT_SHIFT,
    ['E'] = HID_KEYBOARD_E | KEY_MOD_LEFT_SHIFT,
    ['F'] = HID_KEYBOARD_F | KEY_MOD_LEFT_SHIFT,
    ['G'] = HID_KEYBOARD_G | KEY_MOD_LEFT_SHIFT,
    ['H'] = HID_KEYBOARD_H | KEY_MOD_LEFT_SHIFT,
    ['I'] = HID_KEYBOARD_I | KEY_MOD_LEFT_SHIFT,
    ['J'] = HID_KEYBOARD_J | KEY_MOD_LEFT_SHIFT,
    ['K'] = HID_KEYBOARD_K | KEY_MOD_LEFT_SHIFT,
    ['L'] = HID_KEYBOARD_L | KEY_MOD_LEFT_SHIFT,
    ['M'] = HID_KEYBOARD_M | KEY_MOD_LEFT_SHIFT,
    ['N'] = HID_KEYBOARD_N | KEY_MOD_LEFT_SHIFT,
    ['O'] = HID_KEYBOARD_O | KEY_MOD_LEFT_SHIFT,
    ['P'] = HID_KEYBOARD_P | KEY_MOD_LEFT_SHIFT,
    ['Q'] = HID_KEYBOARD_Q | KEY_MOD_LEFT_SHIFT,
    ['R'] = HID_KEYBOARD_R | KEY_MOD_LEFT_SHIFT,
    ['S'] = HID_KEYBOARD_S | KEY_MOD_LEFT_SHIFT,
    ['T'] = HID_KEYBOARD_T | KEY_MOD_LEFT_SHIFT,
    ['U'] = HID_KEYBOARD_U | KEY_MOD_LEFT_SHIFT,
    ['V'] = HID_KEYBOARD_V | KEY_MOD_LEFT_SHIFT,
    ['W'] = HID_KEYBOARD_W | KEY_MOD_LEFT_SHIFT,
    ['X'] = HID_KEYBOARD_X | KEY_MOD_LEFT_SHIFT,
    ['Y'] = HID_KEYBOARD_Z | KEY_MOD_LEFT_SHIFT,
    ['Z'] = HID_KEYBOARD_Y | KEY_MOD_LEFT_SHIFT,
    ['['] = HID_KEYBOARD_8 | KEY_MOD_RIGHT_ALT,
    ['\\'] = HID_KEYBOARD_MINUS | KEY_MOD_RIGHT_ALT,
    [']'] = HID_KEYBOARD_9 | KEY_MOD_RIGHT_ALT,
    ['^'] = HID_KEYBOARD_GRAVE_ACCENT,
    ['_'] = HID_KEYBOARD_SLASH | KEY_MOD_LEFT_SHIFT,
    ['`'] = HID_KEYBOARD_EQUAL_SIGN | KEY_MOD_LEFT_SHIFT,
    ['a'] = HID_KEYBOARD_A,
    ['b'] = HID_KEYBOARD_B,
    ['c'] = HID_KEYBOARD_C,
    ['d'] = HID_KEYBOARD_D,
    ['e'] = HID_KEYBOARD_E,
    ['f'] = HID_KEYBOARD_F,
    ['g'] = HID_KEYBOARD_G,
    ['h'] = HID_KEYBOARD_H,
    ['i'] = HID_KEYBOARD_I,
    ['j'] = HID_KEYBOARD_J,
    ['k'] = HID_KEYBOARD_K,
    ['l'] = HID_KEYBOARD_L,
    ['m'] = HID_KEYBOARD_M,
    ['n'] = HID_KEYBOARD_N,
    ['o'] = HID_KEYBOARD_O,
    ['p'] = HID_KEYBOARD_P,
    ['q'] = HID_KEYBOARD_Q,
    ['r'] = HID_KEYBOARD_R,
    ['s'] = HID_KEYBOARD_S,
    ['t'] = HID_KEYBOARD_T,
    ['u'] = HID_KEYBOARD_U,
    ['v'] = HID_KEYBOARD_V,
    ['w'] = HID_KEYBOARD_W,
    ['x'] = HID_KEYBOARD_X,
    ['y'] = HID_KEYBOARD_Z,
    ['z'] = HID_KEYBOARD_Y,
    ['{'] = HID_KEYBOARD_7 | KEY_MOD_RIGHT_ALT,
    ['|'] = HID_KEYBOARD_NONUS_BACKSLASH | KEY_MOD_RIGHT_ALT,
    ['}'] = HID_KEYBOARD_0 | KEY_MOD_RIGHT_ALT,
    ['~'] = HID_KEYBOARD_CLOSE_BRACKET | KEY_MOD_RIGHT_ALT,
    ['\t'] = HID_KEYBOARD_TAB,
    ['\n'] = HID_KEYBOARD_RETURN,
};

// ES ASCII to HID mapping
static const uint16_t es_asciimap[128] = {
    [' '] = HID_KEYBOARD_SPACEBAR,
    ['!'] = HID_KEYBOARD_1 | KEY_MOD_LEFT_SHIFT,
    ['"'] = HID_KEYBOARD_2 | KEY_MOD_LEFT_SHIFT,
    ['#'] = HID_KEYBOARD_3 | KEY_MOD_RIGHT_ALT,
    ['$'] = HID_KEYBOARD_4 | KEY_MOD_LEFT_SHIFT,
    ['%'] = HID_KEYBOARD_5 | KEY_MOD_LEFT_SHIFT,
    ['&'] = HID_KEYBOARD_6 | KEY_MOD_LEFT_SHIFT,
    ['\''] = HID_KEYBOARD_MINUS,
    ['('] = HID_KEYBOARD_8 | KEY_MOD_LEFT_SHIFT,
    [')'] = HID_KEYBOARD_9 | KEY_MOD_LEFT_SHIFT,
    ['*'] = HID_KEYBOARD_CLOSE_BRACKET | KEY_MOD_LEFT_SHIFT,
    ['+'] = HID_KEYBOARD_CLOSE_BRACKET,
    [','] = HID_KEYBOARD_COMMA,
    ['-'] = HID_KEYBOARD_SLASH,
    ['.'] = HID_KEYBOARD_DOT,
    ['/'] = HID_KEYBOARD_7 | KEY_MOD_LEFT_SHIFT,
    ['0'] = HID_KEYBOARD_0,
    ['1'] = HID_KEYBOARD_1,
    ['2'] = HID_KEYBOARD_2,
    ['3'] = HID_KEYBOARD_3,
    ['4'] = HID_KEYBOARD_4,
    ['5'] = HID_KEYBOARD_5,
    ['6'] = HID_KEYBOARD_6,
    ['7'] = HID_KEYBOARD_7,
    ['8'] = HID_KEYBOARD_8,
    ['9'] = HID_KEYBOARD_9,
    [':'] = HID_KEYBOARD_DOT | KEY_MOD_LEFT_SHIFT,
    [';'] = HID_KEYBOARD_COMMA | KEY_MOD_LEFT_SHIFT,
    ['<'] = HID_KEYBOARD_NONUS_BACKSLASH,
    ['='] = HID_KEYBOARD_0 | KEY_MOD_LEFT_SHIFT,
    ['>'] = HID_KEYBOARD_NONUS_BACKSLASH | KEY_MOD_LEFT_SHIFT,
    ['?'] = HID_KEYBOARD_MINUS | KEY_MOD_LEFT_SHIFT,
    ['@'] = HID_KEYBOARD_2 | KEY_MOD_RIGHT_ALT,
    ['A'] = HID_KEYBOARD_A | KEY_MOD_LEFT_SHIFT,
    ['B'] = HID_KEYBOARD_B | KEY_MOD_LEFT_SHIFT,
    ['C'] = HID_KEYBOARD_C | KEY_MOD_LEFT_SHIFT,
    ['D'] = HID_KEYBOARD_D | KEY_MOD_LEFT_SHIFT,
    ['E'] = HID_KEYBOARD_E | KEY_MOD_LEFT_SHIFT,
    ['F'] = HID_KEYBOARD_F | KEY_MOD_LEFT_SHIFT,
    ['G'] = HID_KEYBOARD_G | KEY_MOD_LEFT_SHIFT,
    ['H'] = HID_KEYBOARD_H | KEY_MOD_LEFT_SHIFT,
    ['I'] = HID_KEYBOARD_I | KEY_MOD_LEFT_SHIFT,
    ['J'] = HID_KEYBOARD_J | KEY_MOD_LEFT_SHIFT,
    ['K'] = HID_KEYBOARD_K | KEY_MOD_LEFT_SHIFT,
    ['L'] = HID_KEYBOARD_L | KEY_MOD_LEFT_SHIFT,
    ['M'] = HID_KEYBOARD_M | KEY_MOD_LEFT_SHIFT,
    ['N'] = HID_KEYBOARD_N | KEY_MOD_LEFT_SHIFT,
    ['O'] = HID_KEYBOARD_O | KEY_MOD_LEFT_SHIFT,
    ['P'] = HID_KEYBOARD_P | KEY_MOD_LEFT_SHIFT,
    ['Q'] = HID_KEYBOARD_Q | KEY_MOD_LEFT_SHIFT,
    ['R'] = HID_KEYBOARD_R | KEY_MOD_LEFT_SHIFT,
    ['S'] = HID_KEYBOARD_S | KEY_MOD_LEFT_SHIFT,
    ['T'] = HID_KEYBOARD_T | KEY_MOD_LEFT_SHIFT,
    ['U'] = HID_KEYBOARD_U | KEY_MOD_LEFT_SHIFT,
    ['V'] = HID_KEYBOARD_V | KEY_MOD_LEFT_SHIFT,
    ['W'] = HID_KEYBOARD_W | KEY_MOD_LEFT_SHIFT,
    ['X'] = HID_KEYBOARD_X | KEY_MOD_LEFT_SHIFT,
    ['Y'] = HID_KEYBOARD_Y | KEY_MOD_LEFT_SHIFT,
    ['Z'] = HID_KEYBOARD_Z | KEY_MOD_LEFT_SHIFT,
    ['['] = HID_KEYBOARD_OPEN_BRACKET | KEY_MOD_RIGHT_ALT,
    ['\\'] = HID_KEYBOARD_GRAVE_ACCENT | KEY_MOD_RIGHT_ALT,
    [']'] = HID_KEYBOARD_CLOSE_BRACKET | KEY_MOD_RIGHT_ALT,
    ['^'] = HID_KEYBOARD_OPEN_BRACKET | KEY_MOD_LEFT_SHIFT,
    ['_'] = HID_KEYBOARD_SLASH | KEY_MOD_LEFT_SHIFT,
    ['`'] = HID_KEYBOARD_OPEN_BRACKET,
    ['a'] = HID_KEYBOARD_A,
    ['b'] = HID_KEYBOARD_B,
    ['c'] = HID_KEYBOARD_C,
    ['d'] = HID_KEYBOARD_D,
    ['e'] = HID_KEYBOARD_E,
    ['f'] = HID_KEYBOARD_F,
    ['g'] = HID_KEYBOARD_G,
    ['h'] = HID_KEYBOARD_H,
    ['i'] = HID_KEYBOARD_I,
    ['j'] = HID_KEYBOARD_J,
    ['k'] = HID_KEYBOARD_K,
    ['l'] = HID_KEYBOARD_L,
    ['m'] = HID_KEYBOARD_M,
    ['n'] = HID_KEYBOARD_N,
    ['o'] = HID_KEYBOARD_O,
    ['p'] = HID_KEYBOARD_P,
    ['q'] = HID_KEYBOARD_Q,
    ['r'] = HID_KEYBOARD_R,
    ['s'] = HID_KEYBOARD_S,
    ['t'] = HID_KEYBOARD_T,
    ['u'] = HID_KEYBOARD_U,
    ['v'] = HID_KEYBOARD_V,
    ['w'] = HID_KEYBOARD_W,
    ['x'] = HID_KEYBOARD_X,
    ['y'] = HID_KEYBOARD_Y,
    ['z'] = HID_KEYBOARD_Z,
    ['{'] = HID_KEYBOARD_APOSTROPHE | KEY_MOD_RIGHT_ALT,
    ['|'] = HID_KEYBOARD_1 | KEY_MOD_RIGHT_ALT,
    ['}'] = HID_KEYBOARD_BACKSLASH | KEY_MOD_RIGHT_ALT,
    ['~'] = HID_KEYBOARD_4 | KEY_MOD_RIGHT_ALT,
    ['\t'] = HID_KEYBOARD_TAB,
    ['\n'] = HID_KEYBOARD_RETURN,
};

uint16_t keyboard_layout_map_char(KeyboardLayout layout, char c) {
    uint8_t uc = (uint8_t)c;
    if(uc > 127) return HID_KEYBOARD_NONE;

    switch(layout) {
    case KeyboardLayoutFR:
        if(fr_asciimap[uc]) return fr_asciimap[uc];
        break;
    case KeyboardLayoutDE:
        if(de_asciimap[uc]) return de_asciimap[uc];
        break;
    case KeyboardLayoutES:
        if(es_asciimap[uc]) return es_asciimap[uc];
        break;
    default:
        break;
    }
    // US layout or fallback
    return HID_ASCII_TO_KEY(c);
}
